<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Arindam-pc" name="postAPITests.SpotTradeTests" tests="10" failures="3" timestamp="08 Sep 2019 20:42:23 GMT" time="2.298" errors="0">
  <testcase name="tc02_spot_value_date_same_as_trade_date" time="0.058" classname="postAPITests.SpotTradeTests"/>
  <testcase name="tc03_spot_value_date_before_trade_date" time="0.056" classname="postAPITests.SpotTradeTests"/>
  <testcase name="tc010_spot_invalid_value_date" time="1.764" classname="postAPITests.SpotTradeTests">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Expected and actual post response status doesn&#039;t match expected [ERROR] but found [SUCCESS],
	Expected and actual Post response messages doesn&#039;t match expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected and actual post response status doesn't match expected [ERROR] but found [SUCCESS],
Expected and actual Post response messages doesn't match expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at postAPITests.SpotTradeTests.validate(SpotTradeTests.java:148)
at postAPITests.SpotTradeTests.tc010_spot_invalid_value_date(SpotTradeTests.java:135)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- tc010_spot_invalid_value_date -->
  <testcase name="tc06_spot_illegal_entity" time="0.054" classname="postAPITests.SpotTradeTests">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Expected and actual post response status doesn&#039;t match expected [ERROR] but found [SUCCESS],
	Expected and actual Post response messages doesn&#039;t match expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected and actual post response status doesn't match expected [ERROR] but found [SUCCESS],
Expected and actual Post response messages doesn't match expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at postAPITests.SpotTradeTests.validate(SpotTradeTests.java:148)
at postAPITests.SpotTradeTests.tc06_spot_illegal_entity(SpotTradeTests.java:91)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- tc06_spot_illegal_entity -->
  <testcase name="tc04_spot_check_supported_counterparty" time="0.045" classname="postAPITests.SpotTradeTests"/>
  <testcase name="tc08_spot_weekend_value_date" time="0.048" classname="postAPITests.SpotTradeTests"/>
  <testcase name="tc01_spot_value_date_after_trade_date" time="0.112" classname="postAPITests.SpotTradeTests"/>
  <testcase name="tc05_spot_unsupported_counterparty" time="0.062" classname="postAPITests.SpotTradeTests"/>
  <testcase name="tc09_spot_value_date_currency_non_working_day" time="0.043" classname="postAPITests.SpotTradeTests">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Expected and actual post response status doesn&#039;t match expected [ERROR] but found [SUCCESS],
	Expected and actual Post response messages doesn&#039;t match expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected and actual post response status doesn't match expected [ERROR] but found [SUCCESS],
Expected and actual Post response messages doesn't match expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at postAPITests.SpotTradeTests.validate(SpotTradeTests.java:148)
at postAPITests.SpotTradeTests.tc09_spot_value_date_currency_non_working_day(SpotTradeTests.java:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- tc09_spot_value_date_currency_non_working_day -->
  <testcase name="tc07_spot_invalid_currency" time="0.056" classname="postAPITests.SpotTradeTests"/>
</testsuite> <!-- postAPITests.SpotTradeTests -->
